//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CandyShop.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocaleEN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocaleEN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CandyShop.Properties.LocaleEN", typeof(LocaleEN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to locate Chocolatey binary. Please set the full path in the configuration file and restart the application. Check the &apos;Extras&apos; menu to quickly navigate to the config file. If this is the first time launching the application or the config file does not exist, it will be created on application exit..
        /// </summary>
        internal static string ERROR_CHOCO_PATH {
            get {
                return ResourceManager.GetString("ERROR_CHOCO_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to disable Candy Shop launch with system start..
        /// </summary>
        internal static string ERROR_DISABLED_START_WITH_SYSTEM {
            get {
                return ResourceManager.GetString("ERROR_DISABLED_START_WITH_SYSTEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve installed packages: {0}.
        /// </summary>
        internal static string ERROR_RETRIEVING_INSTALLED_PACKAGES {
            get {
                return ResourceManager.GetString("ERROR_RETRIEVING_INSTALLED_PACKAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve outdated packages: {0}.
        /// </summary>
        internal static string ERROR_RETRIEVING_OUTDATED_PACKAGES {
            get {
                return ResourceManager.GetString("ERROR_RETRIEVING_OUTDATED_PACKAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve package details: {0}.
        /// </summary>
        internal static string ERROR_RETRIEVING_PACKAGE_DETAILS {
            get {
                return ResourceManager.GetString("ERROR_RETRIEVING_PACKAGE_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error upgrading outdated packages: {0}.
        ///
        ///Hint: Check the output in the Candy Shop console window before pressing OK, or see the logs. (The log folder of the package manager is available through the Extras menu.).
        /// </summary>
        internal static string ERROR_UPGRADING_OUTDATED_PACKAGES {
            get {
                return ResourceManager.GetString("ERROR_UPGRADING_OUTDATED_PACKAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to locate Winget binary. Please set the full path in the configuration file and restart the application. Check the &apos;Extras&apos; menu to quickly navigate to the config file. If this is the first time launching the application or the config file does not exist, it will be created on application exit..
        /// </summary>
        internal static string ERROR_WINGET_PATH {
            get {
                return ResourceManager.GetString("ERROR_WINGET_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore.
        /// </summary>
        internal static string NOT_IGNORE {
            get {
                return ResourceManager.GetString("NOT_IGNORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show more.
        /// </summary>
        internal static string NOT_SHOW {
            get {
                return ResourceManager.GetString("NOT_SHOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} packages are outdated..
        /// </summary>
        internal static string NOT_TEXT_MULTI {
            get {
                return ResourceManager.GetString("NOT_TEXT_MULTI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} package is outdated..
        /// </summary>
        internal static string NOT_TEXT_SINGLE {
            get {
                return ResourceManager.GetString("NOT_TEXT_SINGLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} v{2} for {1}.
        /// </summary>
        internal static string TEXT_APP_TITLE {
            get {
                return ResourceManager.GetString("TEXT_APP_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        internal static string TEXT_CANCEL {
            get {
                return ResourceManager.GetString("TEXT_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        internal static string TEXT_COL_AVAILABLE {
            get {
                return ResourceManager.GetString("TEXT_COL_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        internal static string TEXT_COL_CURRENT {
            get {
                return ResourceManager.GetString("TEXT_COL_CURRENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string TEXT_COL_NAME {
            get {
                return ResourceManager.GetString("TEXT_COL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pinned.
        /// </summary>
        internal static string TEXT_COL_PINNED {
            get {
                return ResourceManager.GetString("TEXT_COL_PINNED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string TEXT_COL_SOURCE {
            get {
                return ResourceManager.GetString("TEXT_COL_SOURCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string TEXT_COL_VERSION {
            get {
                return ResourceManager.GetString("TEXT_COL_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permanently hide this warning?.
        /// </summary>
        internal static string TEXT_HIDE_PERMANENTLY {
            get {
                return ResourceManager.GetString("TEXT_HIDE_PERMANENTLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} License.
        /// </summary>
        internal static string TEXT_LICENSE_TITLE {
            get {
                return ResourceManager.GetString("TEXT_LICENSE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading ....
        /// </summary>
        internal static string TEXT_LOADING {
            get {
                return ResourceManager.GetString("TEXT_LOADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for installed packages.
        /// </summary>
        internal static string TEXT_LOADING_INSTALLED {
            get {
                return ResourceManager.GetString("TEXT_LOADING_INSTALLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for outdated packages.
        /// </summary>
        internal static string TEXT_LOADING_OUTDATED {
            get {
                return ResourceManager.GetString("TEXT_LOADING_OUTDATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open {0} logs.
        /// </summary>
        internal static string TEXT_MENU_LOGS {
            get {
                return ResourceManager.GetString("TEXT_MENU_LOGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to {0} &amp;packages.
        /// </summary>
        internal static string TEXT_MENU_SWITCH {
            get {
                return ResourceManager.GetString("TEXT_MENU_SWITCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected package manager will be executed without administrator privileges. To hide this warning, enable the property &apos;SuppressAdminWarning&apos;. If elevated privileges are required, launch CandyShop as administrator or enable the property &apos;ElevateOnDemand&apos;..
        /// </summary>
        internal static string TEXT_NO_ADMIN_HINT {
            get {
                return ResourceManager.GetString("TEXT_NO_ADMIN_HINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (no administrator privileges).
        /// </summary>
        internal static string TEXT_NO_ADMIN_HINT_SHORT {
            get {
                return ResourceManager.GetString("TEXT_NO_ADMIN_HINT_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A change to the configuration file was detected. Please restart  the application by pressing OK..
        /// </summary>
        internal static string TEXT_PREFERENCES_CHANGED {
            get {
                return ResourceManager.GetString("TEXT_PREFERENCES_CHANGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected packages: {0}.
        /// </summary>
        internal static string TEXT_SELECTED_PACKAGE_COUNT {
            get {
                return ResourceManager.GetString("TEXT_SELECTED_PACKAGE_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Deselect all.
        /// </summary>
        internal static string TEXT_TS_DESELECT {
            get {
                return ResourceManager.GetString("TEXT_TS_DESELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Refresh.
        /// </summary>
        internal static string TEXT_TS_REFRESH {
            get {
                return ResourceManager.GetString("TEXT_TS_REFRESH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh &amp;installed only.
        /// </summary>
        internal static string TEXT_TS_REFRESH_INSTALLED {
            get {
                return ResourceManager.GetString("TEXT_TS_REFRESH_INSTALLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Select all.
        /// </summary>
        internal static string TEXT_TS_SELECT_ALL {
            get {
                return ResourceManager.GetString("TEXT_TS_SELECT_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select &amp;top level packages.
        /// </summary>
        internal static string TEXT_TS_SELECT_SMART {
            get {
                return ResourceManager.GetString("TEXT_TS_SELECT_SMART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade &amp;All.
        /// </summary>
        internal static string TEXT_UPGRADE_ALL {
            get {
                return ResourceManager.GetString("TEXT_UPGRADE_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Upgrade.
        /// </summary>
        internal static string TEXT_UPGRADE_SELECTED {
            get {
                return ResourceManager.GetString("TEXT_UPGRADE_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/weberjonathan/CandyShop.
        /// </summary>
        internal static string URL_GITHUB {
            get {
                return ResourceManager.GetString("URL_GITHUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://docs.chocolatey.org/en-us/faqs#what-is-the-difference-between-packages-no-suffix-as-compared-to.install.portable.
        /// </summary>
        internal static string URL_META_PACKAGES {
            get {
                return ResourceManager.GetString("URL_META_PACKAGES", resourceCulture);
            }
        }
    }
}
