//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CandyShop.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocaleEN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocaleEN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CandyShop.Properties.LocaleEN", typeof(LocaleEN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve package info. An error occurred during the execution of Chocolatey..
        /// </summary>
        internal static string Err_GetInfo {
            get {
                return ResourceManager.GetString("Err_GetInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve list of installed applications. An error occurred during the execution of Chocolatey..
        /// </summary>
        internal static string Err_ListInstalled {
            get {
                return ResourceManager.GetString("Err_ListInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration privileges are required for this operation..
        /// </summary>
        internal static string Err_RequireAdmin {
            get {
                return ResourceManager.GetString("Err_RequireAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve outdated packages: {0}.
        /// </summary>
        internal static string ERROR_RETRIEVING_OUTDATED_PACKAGES {
            get {
                return ResourceManager.GetString("ERROR_RETRIEVING_OUTDATED_PACKAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} v{1}.
        /// </summary>
        internal static string TEXT_APP_TITLE {
            get {
                return ResourceManager.GetString("TEXT_APP_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        internal static string TEXT_CANCEL {
            get {
                return ResourceManager.GetString("TEXT_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        internal static string TEXT_COL_AVAILABLE {
            get {
                return ResourceManager.GetString("TEXT_COL_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        internal static string TEXT_COL_CURRENT {
            get {
                return ResourceManager.GetString("TEXT_COL_CURRENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string TEXT_COL_NAME {
            get {
                return ResourceManager.GetString("TEXT_COL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pinned.
        /// </summary>
        internal static string TEXT_COL_PINNED {
            get {
                return ResourceManager.GetString("TEXT_COL_PINNED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} License.
        /// </summary>
        internal static string TEXT_LICENSE_TITLE {
            get {
                return ResourceManager.GetString("TEXT_LICENSE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading ....
        /// </summary>
        internal static string TEXT_LOADING {
            get {
                return ResourceManager.GetString("TEXT_LOADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candy Shop does not have administrator privileges. Proceed with caution!.
        /// </summary>
        internal static string TEXT_NO_ADMIN_HINT {
            get {
                return ResourceManager.GetString("TEXT_NO_ADMIN_HINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (no administrator privileges).
        /// </summary>
        internal static string TEXT_NO_ADMIN_HINT_SHORT {
            get {
                return ResourceManager.GetString("TEXT_NO_ADMIN_HINT_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade &amp;All.
        /// </summary>
        internal static string TEXT_UPGRADE_ALL {
            get {
                return ResourceManager.GetString("TEXT_UPGRADE_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Upgrade ({0}).
        /// </summary>
        internal static string TEXT_UPGRADE_SELECTED {
            get {
                return ResourceManager.GetString("TEXT_UPGRADE_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/weberjonathan/CandyShop.
        /// </summary>
        internal static string URL_GITHUB {
            get {
                return ResourceManager.GetString("URL_GITHUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://docs.chocolatey.org/en-us/faqs#what-is-the-difference-between-packages-no-suffix-as-compared-to.install.portable.
        /// </summary>
        internal static string URL_META_PACKAGES {
            get {
                return ResourceManager.GetString("URL_META_PACKAGES", resourceCulture);
            }
        }
    }
}
